#  ┬─┐┬─┐┬─┐  ┌─┐┌─┐┌┌┐┌┌┐o┌┐┐
#  │─┘│┬┘├─ ──│  │ ││││││││ │ 
#  ┘  ┘└┘┴─┘  └─┘┘─┘┘ ┘┘ ┘┘ ┘ 

repos:
- repo: https://github.com/zricethezav/gitleaks
  rev: v8.21.2
  hooks:
  - id: gitleaks
    args:
    - --config=gitleaks.toml
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
    - id: check-merge-conflict
    - id: end-of-file-fixer
- repo: local
  hooks:
    # https://github.com/golangci/golangci-lint/blob/master/.pre-commit-hooks.yaml
    - id: golangci-lint-config-verify
      name: golangci-lint-config-verify
      description: Verifies the configuration file
      entry: golangci-lint config verify
      files: '\.golangci\.(?:yml|yaml|toml|json)'
      language: golang
      pass_filenames: false
    - id: golangci-lint
      name: golangci-lint
      description: Fast linters runner for Go. Note that only modified files are linted, so linters like 'unused' that need to scan all files won't work as expected.
      entry: golangci-lint run --new-from-rev HEAD --fix
      types: [go]
      language: golang
      require_serial: true
      pass_filenames: false
