name: Build

on:
  push:
    branches:
      - main
    tags-ignore:
      - v*

permissions:
  packages: write

jobs:
  test:
    runs-on: ubuntu-latest
    name: Lint and Test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Lint
        uses: golangci/golangci-lint-action@v6

      - name: Install packages
        run: go mod tidy

      - name: Run tests
        run: go test -v ./... -ginkgo.v

  build:
    runs-on: ubuntu-latest
    name: Build
    needs: [test]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Remove windows and darwin from goos
        run: sed -ri '/- (windows|darwin)$/d' .goreleaser.yaml

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          args: release --clean --fail-fast --snapshot --skip=archive
        env:
          GITHUB_TOKEN: ${{ github.token }}
      
      - name: Docker push
        run: docker push --all-tags 'ghcr.io/${{ github.repository }}'

      - name: Docker create manifest
        run: >-
          docker image ls 'ghcr.io/${{ github.repository }}' --format='{{printf "%s:%s" .Repository .Tag}}' |
          tee docker-images.txt |
          xargs docker buildx imagetools create --tag 'ghcr.io/${{ github.repository }}:latest'

      - name: Cache docker-images.txt
        uses: actions/cache/save@v4
        with:
          path: docker-images.txt
          key: docker-images.txt-${{ github.sha }}
